- .changeset/lazy-mirrors-kick.md
- examples/basic/index.ts
- packages/core/src/prompts/prompt.ts
- packages/prompts/README.md
- packages/prompts/src/index.ts
Closes #26. Closes #27.
There was an existing `initialValue` option, it just wasn't wired up properly for the `text` component. Now it is!
> Support `initialValue` in text prompt

- .changeset/cyan-onions-help.md
- packages/prompts/LICENSE
- packages/prompts/package.json
- packages/prompts/src/index.ts
Closes #31
Vendors `ansi-regex` from https://github.com/chalk/ansi-regex, licensed under the MIT license. Updates LICENSE information for `@clack/prompts`
> chore: vendor ansi-regex

- .changeset/little-papayas-watch.md
- examples/basic/index.ts
- packages/core/src/prompts/multi-select.ts
- packages/prompts/src/index.ts
`initialValue` should set to `selectedValue`, not be the place that cursor at.
I created a new property `cursorAt` to cover the old logic.
Before:
After:
> fix: multiple select initialValue incorrect logic

- .changeset/poor-snakes-beam.md
- packages/core/src/prompts/prompt.ts
Apart from closing the readline interface, the write sink piped to the input needs to be detached.
Fixes https://github.com/natemoo-re/clack/issues/40
> fix(#40): unpipe sink on close

- .changeset/bright-eagles-happen.md
- packages/prompts/src/index.ts
Fixes #44 
Types updated to include number and boolean values without losing typesafety
> Support booleans and numbers in select values

- .changeset/heavy-fishes-change.md
- packages/core/src/prompts/multi-select.ts
- packages/prompts/README.md
- packages/prompts/src/index.ts
close #41 
It would be a little more flexible if we could use empty arrays in the multi-select prompt.
First, I think simply be used as an option (any thoughts are welcome)
> Support `isAllowEmpty` in multi-select prompt

- .changeset/young-dragons-add.md
- examples/basic/index.ts
- packages/prompts/src/index.ts
- pnpm-lock.yaml
- `definePromptGroup` - Typescript safe & easy way to define group of prompts that return JSON of all the prompts consolidated into one.
- `definePrompt` - A way to define a prompt with the options by itself or within a group that will require a user to add additional name prop to then drive typescript to validate the options that correspond to the type
Make it easy to define prompts without multiple imports and that is type safe and is able to wrap into a group with additional hook that will act as the global `onCancel` to handle all cancel events within a prompt.
This example is showing that it will set a global on cancel without modifying the core package that is handled by the wrapper and will run prompts in order of the array struct. This is typescript safe and will autocomplete …
> feat: `group`

- .changeset/witty-icons-try.md
- packages/prompts/README.md
Updated README.md to include `group` function
> chore: add `group` to readme

- .changeset/tough-plums-greet.md
- packages/core/src/prompts/multi-select.ts
- packages/prompts/src/index.ts
Debugging #63, I found room for improvements of the `multiselect` prompt.
- Move options type closer to implementation
- Move required validation to styled component (we don't want styles in the headless core components)
- Remove intermediate state, always keep `value` up-to-date
- Use immutable, instead of mutating underlying, data structures 
- Remove error prone type casts
- Remove superfluous `return` handler
- Don't do `close()` on submit (already taken care of in base prompt and not always desired)
- Replace init guard
- Fix parameter type for `validate()`
- Remove non-existing cursor key case
- Remove unused parameter
Fixes #63.
> ref: multiselect 

- .changeset/long-bees-turn.md
- examples/basic/index.ts
- packages/core/src/prompts/password.ts
- packages/prompts/src/index.ts
I noticed that `@clack/prompts` doesn't export a password prompt, and I needed it in a project I'm currently working on 😅
Let me know if I should make any changes.
> feat: add password prompt to `@clack/prompts`

- .changeset/dull-tools-cry.md
- packages/core/src/prompts/multi-select.ts
- packages/core/src/prompts/prompt.ts
- packages/prompts/src/index.ts
- Return `Value[]` instead of `Option[]`
- Fix type of validate parameter (somehow got lost in last PR...)
Fixes #67.
> fix(#67): multiselect return

- packages/core/src/prompts/password.ts
Decided not to do the `extends TextPrompt` since there were competing event listeners.
> password: split()+map()+join() -> replaceAll()

- .changeset/hot-candles-repeat.md
- packages/prompts/src/index.ts
No docs, nor examples, yet, but working implementation to play with.
Closes #71.
> feat: add log

- .changeset/dull-boats-drum.md
- .changeset/tasty-comics-warn.md
- examples/changesets/index.ts
- examples/changesets/package.json
- examples/changesets/tsconfig.json
- package.json
- packages/core/src/index.ts
- packages/core/src/prompts/group-multiselect.ts
- packages/core/src/prompts/multi-select.ts
- packages/prompts/src/index.ts
https://user-images.githubusercontent.com/7118177/220904083-cd999bad-2ace-4880-b9f2-8aeb4653d9db.mp4
> Add changeset-like prompts, changeset demo

- .changeset/olive-birds-brush.md
- packages/prompts/src/index.ts
Select prompts (incl. multi + group-multi):
- simplify option value types
- support complex value types
Fixes #44 (for realz). 
**Note:** `selectKey` is not supported since it requires `value` to be `string`.
> fix(#44) complex values

- .editorconfig
- .gitattributes
- .vscode/settings.json
Added:
- `.editorconfig` to configure Editors
- `.gitattributes` to configure Git
- `.vscode` to tell VSCode to use the local TypeScript version instead of the global
> chore: add editor files

- package.json
- packages/core/package.json
- packages/prompts/package.json
- pnpm-lock.yaml
`unbuild` is used by all the packages so it doesn't need to be a dev-dependency in all of them—just the root is fine.
> chore: move unbuild to the root `package.json`

- .changeset/good-islands-provide.md
- packages/core/package.json
- packages/core/src/prompts/prompt.ts
- pnpm-lock.yaml
Closes #87.
- Bundles `wrap-ansi`. Kind of a bummer, but it's battle-tested and works very well. Ideally we'll continue exploring our own, smaller version on the [`feat/wrap`](https://github.com/natemoo-re/clack/tree/feat/wrap) branch.
- Automatically wraps prompts to properly calculate visual line offset for each frame
- Also re-wraps the previous frame in case the columns have changed. This allows the line calculation to stay up-to-date.
> Fix line duplication bug with proper line wrapping

- .github/workflows/lint.yml
- package.json
- tsconfig.json
Since unbuild doesn't type-check, there's been quite a few type-errors that got in.
Now CI will run TypeScript to make sure there are no errors.
> ci: setup type-checking on PRs

- packages/prompts/src/index.ts
This PR aims to improve type readability of `group` function, introducing `Prettify` type, which unwrap all the complex intern types to a top level one.
```ts
type Prettify<T> = {
[P in keyof T]: T[P]
} & {}
```
It adds `Prettify` to `group` return type:
```ts
//before 
declare function group<T>(
prompts: PromptGroup<T>,
opts?: PromptGroupOptions<T>
): Promise<PromptGroupAwaitedReturn<T>>;
const result = await group({ foo: () => text({} as any) });
//    ^? const result: PromptGroupAwaitedReturn<{ foo: string | symbol }>
// after
declare function group<T>(
prompts: PromptGroup<T>,
opts?: PromptGroupOptions<T>
): Promise<Prettify<PromptGroupAwaitedReturn<T>>>;
const result = await group({ foo: () => text({} as any) });
//    ^? const result: { foo: string }
```
And to `results` param, I …
> feat: improve group `types` for readability

- .changeset/twelve-shrimps-report.md
- packages/core/src/utils.ts
The fix introduced by #80 seems to prevent control sequences from being sent. Restoring raw mode on top of that makes it work again.
Fixes #103
> fix(#103): restore raw mode on unblock

- packages/prompts/src/index.ts
This PR addresses in an issue discussed in #44, where `select` fields with non-primitive values (originally introduced in #86) are not properly inferring the type of the returned user selection.
I did so by removing the `Options` generic from all fields as, from what I can tell, it's effectively representing the same constraint as `Value`. Typechecking for the build still passes, but there's a chance I broke type inference in some other use case - please double check me here!
> Fix complex value return type inference

- .changeset/red-seas-try.md
- packages/prompts/src/index.ts
This PR adds registration and clear steps to spinner's hooks
> fix(@clack/prompts): clear `spinner`'s hooks on `spinner.stop`

- .changeset/curvy-lobsters-tell.md
- packages/prompts/README.md
- packages/prompts/src/index.ts
Run tasks like listr.
This pr includes:
Maybe closes: #152
> feat(@clack/prompts): add tasks

- .changeset/olive-walls-clean.md
- packages/core/src/utils.ts
Fix #176 
The issue occurred on Windows, when the await line between the spinner start and stop was present, causing the second following prompt to be unresponsive to key inputs (e.g., arrow keys or Ctrl-C), except for the [Enter] key. Additionally, this resulted in the duplication of the first option.
The solution is identify when it is running on Windows and do not change terminal's mode
```ts
if (input.isTTY && !isWindows) input.setRawMode(false);
```
OS: Windows, Ubuntu
Node Version: v18.17.1
Package: @clack/prompts
Package Version: v0.7.0
```ts
const sp = p.spinner();
sp.start("start");
await setTimeout(2000);
sp.stop("stop");
const y = await p.confirm({
message: "Test anyway?",
});
const x = await p.multiselect({
message: "test",
options: [
{ value: "a", label: "A", hint: "hint A" …
```
> fix(@clack/core): keyboard input not working after await in spinner

- .changeset/light-laws-judge.md
- packages/prompts/src/index.ts
This PR introduces a `maxItems` calculation based on available terminal rows. This ensures a responsive display, preventing issues caused by lists that might exceed the terminal's row capacity.
https://github.com/natemoo-re/clack/assets/100330057/67d437fc-9d50-4241-aea6-a0b7710f6a3b
Closes #173
> feat(@clack/prompts): dynamic max items

- .changeset/plenty-days-study.md
- LICENSE
- packages/core/LICENSE
Adds missing `LICENSE` file to the `@clack/core`. Since it has always been marked as MIT in `package.json`, please consider this a licensing clarification rather than a licensing change.
Closes #206
> add missing license file

- .changeset/gold-dryers-bake.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
- packages/core/package.json
- packages/core/src/utils.ts
- packages/core/test/mock-readable.ts
- packages/core/test/mock-writable.ts
- packages/core/test/prompts/prompt.test.ts
- packages/core/test/utils.test.ts
- packages/prompts/src/index.ts
- pnpm-lock.yaml
Adds some tests for the core package and fixes a small bug found during writing them.
The bug is basically that we never unhide the cursor on `process.exit` conditions, meaning we leave it hidden in the terminal after our prompt has been cancelled.
cc @natemoo-re  i was trying to get my head around how this codebase works etc so wrote these while i was in there. they're not as nice as some kind of e2e cli test i suppose, but still seem straight forward enough (and better than nothing)
> test(core): add initial tests

- packages/prompts/README.md
Currently if we just copy the example code of [cancellation](https://github.com/natemoo-re/clack/tree/main/packages/prompts#cancellation), it will throw an error:
```
TypeError: Cannot read properties of undefined (reading 'validate')
```
It might be useful to fill in the required parameters here to ensure that newbies don't get an error when copying this code~
> chore(@clack/prompts): update readme

- .changeset/seven-fireants-cover.md
- packages/core/src/prompts/text.ts
Previously, the cursor position for `TextPrompt` was rendered as off-by-one.
By moving the cursor logic from a `on('value')` handler to a `get valueWithCursor()` property, the cursor position will be correctly calculated as the `valueWithCursor` property is accessed.
> Fixes cursor position for TextPrompt

- .changeset/red-glasses-grin.md
- packages/core/src/prompts/text.ts
Some terminals don't support the `hidden` escape sequence, which leaves the `_` character visible. This PR switches to the `█` character, which should work everywhere.
Unfortunately, a regular space (` `) doesn't seem to display a background color when it's the last character on a line.
Closes #127.
> Use block character as cursor placeholder

- .changeset/slimy-dolphins-press.md
- packages/prompts/LICENSE
- packages/prompts/src/index.ts
Turns out `node:util` has a [`stripVTControlCharacters`](https://nodejs.org/docs/latest/api/util.html#utilstripvtcontrolcharactersstr) function!
As such, we no longer need our own [`ansi-regex`](https://github.com/chalk/ansi-regex) fork.
> Replace custom ANSI regex logic with Node built-in

- build.preset.ts
- package.json
- packages/core/src/prompts/prompt.ts
- pnpm-lock.yaml
- Continues existing work towards #219
- The build was failing in [fork/isolated-decl](https://github.com/bombshell-dev/clack/tree/fork/isolated-decl) due to a bug in unbuild.
- Added a workaround.
- CI is green https://github.com/lilnasy/clack/actions/runs/12629968491/job/35188927126
> fix(isolated decl): get the build to run

- .changeset/moody-hairs-learn.md
- packages/core/src/prompts/prompt.ts
- packages/prompts/src/index.ts
> feat(@clack/core,@clack/prompts): add `Error` support for `prompt.validate`

- tsconfig.json
This pull request includes updates to the tsconfig.json file, aligning it with modern development practices. The changes introduced are as follows:
- `"moduleResolution": "Bundler"`: This option is configured for use with bundlers. Unlike the Node.js resolution modes, this setting supports package.json "imports" and "exports" without requiring file extensions on relative paths in imports.
- `"moduleDetection": "force"`: Enabling this option ensures that every non-declaration file is treated as a module, providing a more consistent and predictable module handling approach.
- `"isolatedModules": true`: TypeScript will now issue warnings for code that might not be correctly interpreted by a single-file transpilation process, helping catch potential issues early in the development process.
- …
> chore: improve tsconfig

- examples/basic/spinner-ci.ts
- packages/core/package.json
- packages/core/src/utils/index.ts
- packages/prompts/README.md
- packages/prompts/package.json
Update from https://github.com/natemoo-re/clack to https://github.com/bombshell-dev/clack
I also updated the `repository.url` in `package.json` with `git+` and `.git` as it's recommended by npm: https://docs.npmjs.com/cli/v11/configuring-npm/package-json#repository
> chore: update repository url

- packages/prompts/README.md
I've noticed that the image showcasing different `log` fuctions isn't displaying correctly. This pull request addresses the syntax issue to ensure the image appears as intended.
> docs(prompts): fix logs image display

- .changeset/pre.json
- README.md
This PR enters `alpha` pre-release mode on `main`.
While there hasn't been much activity on this project recently, many projects have already adopted the `v0` releases in production. Although semantic versioning allows for breaking changes on the minor release of the `v0` major, this wouldn't provide a very stable experience for our existing users.
By moving to the `alpha` pre-release, we're clearly indicating that this is a new chapter for Clack.
We plan to backport critical bug fixes to the [`v0`](https://github.com/bombshell-dev/clack/tree/v0) branch, but don't expect to release any more `v0` minors with new features or breaking changes.
> chore: v1-alpha

- .changeset/legal-bags-tie.md
- .github/workflows/lint.yml
- build.preset.ts
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/prompts/confirm.ts
- packages/core/src/prompts/group-multiselect.ts
- packages/core/src/prompts/multi-select.ts
- packages/core/src/prompts/password.ts
- packages/core/src/prompts/prompt.ts
- packages/core/src/prompts/select-key.ts
- packages/core/src/prompts/select.ts
- packages/core/src/prompts/text.ts
- packages/core/src/types.ts
- packages/core/src/utils/index.ts
- packages/prompts/package.json
- pnpm-workspace.yaml
- tsconfig.json
Migrates to emitting only ES modules now that `require(esm)` is supported in all LTS versions of node other than the soon-to-die-off 18.x.
> feat!: move to esm-only

- .changeset/lemon-monkeys-help.md
- packages/core/src/prompts/prompt.ts
This PR fixes the following error happening on Windows for non-tty terminals.
> TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)
The error was happening this line.
https://github.com/bombshell-dev/clack/blob/d6d9ce791e33dbd40191a47f12db74d19bfbdb8d/packages/core/src/prompts/prompt.ts#L136
It seems calling `new tty.WriteStream` with non-tty file descriptor throws the error above.
I changed `tty.WriteStream` with `stream.Writable` and set `terminal: true` option for `readline.createInterface` so that readline will treat `stream.Writable` as a terminal.
I first went with replacing `new WriteStream(0)` with `isatty(0) ? new WriteStream(0) : fs.createWriteStream(null, { fd: 0 })`. It worked locally, but that didn't pass the tests.
refs #192
> fix: uv_tty_init error on Windows

- .github/workflows/preview.yml
In my fork branch I got [an error](https://github.com/bluwy/clack/actions/runs/14132909943/job/39597513003) when running the preview workflow. A repo check should help prevent it and potentially mistakenly publishing it if someone has pkg.pr.new app setup.
> ci: skip running preview workflow in forks

- .changeset/free-wasps-decide.md
- packages/core/src/prompts/group-multiselect.ts
- packages/prompts/src/index.ts
Adds a `selectableGroups` boolean flag which can be used to disallow selecting groups.
This basically just skips over them when using up/down, but still renders when they are "selected" (by selecting all the children individually).
> feat: add `selectableGroups` option to group multi-select

- .github/workflows/release.yml
Adding the `v0` branch to our release workflow for backports
> chore(ci): allow release from v0 branch

- package.json
- packages/prompts/src/__snapshots__/index.test.ts.snap
- packages/prompts/src/index.test.ts
pnpm seems to strip colours when running parallel tasks (via the `-r` flag). This results in our snapshots mismatching since all of our tests output without colours.
This change basically adds the `--color` flag to force it not to do this, so the snapshots match.
> chore: enable colours when running pnpm

- .changeset/orange-deers-battle.md
- examples/basic/spinner-cancel-advanced.ts
- examples/basic/spinner-cancel.ts
- packages/prompts/src/index.ts
> feat(prompts): add cancellation support for spinners

- .changeset/healthy-candles-admire.md
- packages/prompts/src/index.ts
Allows all prompts to take a custom `output` or `input` which defaults to `process.stdout` and `process.stdin` respectively.
> feat: add `CommonOptions` so all prompts accept a custom output/input

- packages/prompts/src/__snapshots__/index.test.ts.snap
- packages/prompts/src/index.test.ts
Adds more tests for validation in text prompts.
> test: add tests for validation errors

- CONTRIBUTING.md
> docs: add contributing guidelines for Clack

- .github/workflows/release.yml
- package.json
> ci: update release workflow and add jsr job

- .changeset/happy-parents-explain.md
- packages/prompts/src/__snapshots__/index.test.ts.snap
- packages/prompts/src/index.test.ts
- packages/prompts/src/index.ts
Adds a `groupSpacing` option.
If set to something more than `0`, it adds spacing between the groups.
This is another svelte port. They have `spacedGroups` but I decided to make it a little more flexible here
> feat: add `groupSpacing` option to group multi select

- .changeset/empty-buses-wonder.md
- packages/prompts/src/__snapshots__/index.test.ts.snap
- packages/prompts/src/index.test.ts
- packages/prompts/src/index.ts
This adds a new `format` option for formatting lines in a note.
For example:
```ts
// make all lines cyan
note('message', 'title', {
format(str) {
return colors.cyan(str);
}
});
// don't colour lines at all
note('message', 'title', {
format(str) {
return str;
}
});
// add extra text to each line
note('message', 'title', {
format(str) {
return `more text ${str} more text';
}
});
```
cc @AdrianGonz97
> feat: add `format` option to `note` prompt

- .editorconfig
- packages/prompts/src/__snapshots__/index.test.ts.snap
- packages/prompts/src/index.test.ts
- packages/prompts/src/index.ts
Fix #226 
---
~~Update `.editorconfig` to avoid trimming trailing space:~~
- ~~in `.snap` files as they contain "raw" CLI output~~
- ~~in `.md` files as `  `+<kbd>enter</kbd> is translated in `<br>`~~
> fix(prompts): don't strip dots in spinner stop

- .changeset/famous-turkeys-burn.md
- packages/prompts/README.md
- packages/prompts/src/__snapshots__/index.test.ts.snap
- packages/prompts/src/index.test.ts
- packages/prompts/src/index.ts
Adds a new taskLog prompt which renders messages then ultimately does one of the following:
- If error, retain the output and render the error message
- If success, clear the output and render the success message
For example:
```ts
const log = prompts.taskLog({
message: 'some message'
});
log.message('a line of text');
log.message('another line of text');
log.message('multiple\nlines\nof\ntext');
// at this point, it will have rendered like so:
// o some message
// | a line of text
// | another line of text
// ...
log.error('some error');
// if the line above runs, it will render like so:
// x some error
// | a line of text
// | another line of text
// ...
log.success('some success');
// if the line above runs, it will clear and render like so:
// o some success
```
part of bringing …
> feat: add taskLog prompt

- packages/prompts/src/index.ts
No clue why these got here, was probably me running `:read !ll src` in vim.
> fix: remove invalid exports

- package.json
- pnpm-lock.yaml
- tsconfig.json
This means we can directly execute our examples one day.
Related to #291
> chore: enable `erasableSyntaxOnly` in typescript

- packages/prompts/README.md
Closes #296 
Update the README of `@clack/prompts` to add the progress prompt
> docs(prompts): Update README

- packages/prompts/test/__snapshots__/progress-bar.test.ts.snap
- packages/prompts/test/__snapshots__/spinner.test.ts.snap
- packages/prompts/test/progress-bar.test.ts
- packages/prompts/test/spinner.test.ts
These should be two tests. Otherwise, if one fails mid-way through, vitest will think the later snapshot is obsolete and could risk someone removing it by pressing 'u'.
depends on #299
> test: separate cancel/error tests in progressbar/spinner

- .changeset/thin-socks-travel.md
- packages/prompts/src/spinner.ts
- packages/prompts/test/__snapshots__/spinner.test.ts.snap
- packages/prompts/test/spinner.test.ts
Great work on clack! I was eager to have a custom spinner option so I figured I could contribute back to the project. Happy to adjust the implementation if not conform requirements.
Supports a 'custom' indicator on the spinner for settings custom frames and speed:
```ts
export const customSpinner = spinner({
indicator: "custom",
custom: {
frames: ["🦨", "🐎", "🌵", "🤠", "💘", "🧨", "🌮", "🥃", "🏜️"],
speed: 500,
},
});
```
> feat(@clack/prompts): custom spinner indicator support

- package.json
It fails anyway, so we should remove it for now until we get time to fix it.
> chore: temporarily drop JSR release

- .changeset/mean-mice-train.md
- examples/basic/text-validation.ts
- packages/core/src/prompts/prompt.ts
- packages/core/test/prompts/prompt.test.ts
When using text prompts with `initialValue` and `validate` props, validation was not being triggered for incorrect initial values. Users had to press enter first to see validation messages.
This fix:
- Validates initial values as soon as they are set
- Shows validation messages immediately for invalid initial values
- Maintains the prompt in error state until a valid value is entered
Added a couple of tests and an example.
Closes: #315
> fix: validate initial values

- .changeset/moody-baboons-greet.md
- packages/core/src/prompts/autocomplete.ts
- packages/core/test/prompts/autocomplete.test.ts
When `multiple: false` of an auto complete prompt, we should be setting the initial value (i.e. the selected value) as the first one in the list.
This way, when pressing `<RETURN>` without any movement, the result will be the first value.
When `multiple: true`, this will leave the result as `[]`.
Fixes #331
> fix(autocomplete): use first option as initial value in non-multiple

- .changeset/mean-turkeys-help.md
- packages/core/src/prompts/autocomplete.ts
- packages/core/src/prompts/prompt.ts
- packages/core/test/prompts/prompt.test.ts
- packages/prompts/src/autocomplete.ts
- packages/prompts/src/text.ts
- packages/prompts/test/__snapshots__/autocomplete.test.ts.snap
- packages/prompts/test/autocomplete.test.ts
- packages/prompts/test/text.test.ts
This changes how we deal with placeholders.
Currently, a placeholder behaves as a visual hint of what we want the user to type. It also behaves as an optional default value, in that you can press `<Enter>` or `<Tab>` to insert it as the value.
This is confusing since it means it is a "partial" default value, and a placeholder at the same time.
This change basically removes the placeholder logic from core, such that the `text` and `autocomplete` prompts use `placeholder` purely as a render/visual hint.
This updated behaviour means we render the placeholder when no value is set, but it can no longer be inserted as a value. To achieve that, you should combine `defaultValue` with `placeholder` (i.e. set them to the same value).
cc @dreyfus92 @natemoo-re
> fix: treat placeholders as visual element

- .github/workflows/ci.yml
We run CI against _targets_ right now (`main`), rather than the PR itself. This change should mean we run CI against the PR branch.
> chore: run CI against PRs

- .changeset/sharp-lemons-build.md
- packages/prompts/src/common.ts
- packages/prompts/src/task-log.ts
- packages/prompts/test/__snapshots__/task-log.test.ts.snap
- packages/prompts/test/task-log.test.ts
- packages/prompts/test/test-utils.ts
This allows you to have tasklog groups.
Basically this:
```ts
const log = p.taskLog({
title: 'yes?',
limit: 5,
});
const group0 = log.group('group 0');
const group1 = log.group('group 1');
await Promise.all([
(async () => {
for (let i = 0; i < 10; i++) {
group0.message(`foo ${i} bar`);
await new Promise((r) => {
setTimeout(r, 1000);
});
}
group0.success('group 0 done!');
})(),
(async () => {
for (let i = 0; i < 10; i++) {
group1.message(`foo ${i} bar`);
await new Promise((r) => {
setTimeout(r, 500);
});
}
group1.success('group 1 done!');
})(),
]);
await new Promise((r) => {
setTimeout(r, 1000);
});
log.success('yes!');
```
this will result in a scrolling task log whose sub-logs have a `limit: 5` (i.e. the overall log has no such limit)
once inner logs complete, they collapse as normal …
> feat: tasklog groups

- biome.json
- examples/basic/path.ts
- examples/basic/progress.ts
- examples/changesets/index.ts
- package.json
- packages/core/package.json
- packages/core/test/mock-writable.ts
- packages/core/test/prompts/confirm.test.ts
- packages/core/test/prompts/select.test.ts
- packages/prompts/package.json
- packages/prompts/src/path.ts
- packages/prompts/src/spinner.ts
- pnpm-lock.yaml
Bumps a few dev dependencies, and fixes some audits.
> chore: bump various dependencies

- .changeset/shy-ideas-shout.md
- packages/prompts/src/box.ts
- packages/prompts/src/common.ts
- packages/prompts/src/index.ts
- packages/prompts/test/__snapshots__/box.test.ts.snap
- packages/prompts/test/box.test.ts
Adds a new `box` prompt which works like so:
```ts
prompts.box(
'This is a message',
'This is a title',
{
rounded: true
}
);
```
Feedback i'd like on this:
- Does `includePrefix` make sense? Basically its to tell the box to output the usual `|` bar before it, so if it is part of a group of prompts it will fit in. If you set it to `false` (the default), it won't output this
- This is very similar to the `note` prompt. It may be argued that we should just add the functionality to that instead of having a separate prompt
> feat: box prompt

- .changeset/rich-plants-call.md
- packages/prompts/src/group-multi-select.ts
@43081j , It is an amazing library and helps me a lot. Thanks for all your work in this repo.
I see we have precise type in this [link](https://github.com/bombshell-dev/clack/blob/main/packages/core/src/prompts/group-multiselect.ts#L12). 
So should we use more accurate type to replace `any` in another file? This will make our code clearer. If you have some suggestions for this pr. Please tell me directly. Thanks again.
> types: use more accurate type to replace any

- packages/prompts/README.md
The task example doesn't have api import. So I think we should add api import for task example like other examples.
> docs: add import for tasks example

- .changeset/great-lies-dance.md
- packages/prompts/src/note.ts
- packages/prompts/test/__snapshots__/note.test.ts.snap
This PR contains a change i forgot add on #376. The change is **"Do hard wrap"**.
> fix(note): hard wrap

- examples/basic/text-validation.ts
The type of `value` should be `string`,  maybe we can add type assert to pass this type check.
> docs: add type assert for text validation example

- .changeset/tough-crews-flow.md
- packages/core/src/utils/index.ts
- packages/prompts/test/note.test.ts
- packages/prompts/test/test-utils.ts
Mostly for tests, so we can set the `columns`.
Previously, the `Object.assign` in tests was no-op as we'd always return
`80`.
> fix: allow non-writestream writables to have columns
